### ISSUE TITLE
Can i pre-train with a 1070 8gb vram 

### ISSUE THREAD

**Issue by StephennFernandes** [floleuerer/fastai_ulmfit#2]
Hey i have a very basic and simple laptop compared to beefed up deep learning rigs. 

I have an RTX1070( 8GB ), 16GB of RAM,  8th gen i7

Would it be enough to pre-train the ULMfit LM ?

**Comment by floleuerer** [comment]
Hi Stephen, 

yes, shouldn't be a problem. With fp16 and batch size 128 training requires less than 6 GB VRAM. If the card doesn't support fp16 you'll probably have to decrease the batch size. But I can't tell how long the training will take on your laptop. Do you run linux or windows / wsl? I just tested the repo on linux. 

If you have further questions let me know.

Florian

**Comment by StephennFernandes** [comment]
@floleuerer Hey thanks man, thanks a lot for replying and your concern. Yeah so i guess i'd stick with a lower batch size and long hours of training. 


- I see you have trained ulmfit with fastaiV2 ive been trying to code ulmfit with the original 1.0 fastai code. 
 **Are there any changes or improvements in training ULMfit with v2 ?**
I see sentencepiece being used in v2 which wasnt the case in v1

- Also **do happen to know any github repo where i can train ULMFit from scratch with pure Pytorch?** just for learning pourposes. 

and also yeah i do run Linux Ubuntu 18.04

**Comment by floleuerer** [comment]
> * I see you have trained ulmfit with fastaiV2 ive been trying to code ulmfit with the original 1.0 fastai code.
>   **Are there any changes or improvements in training ULMfit with v2 ?**
>   I see sentencepiece being used in v2 which wasnt the case in v1

I don't know if there are differences between fastai1 and fastai2. Whats your idea behind using v1?

> * Also **do happen to know any github repo where i can train ULMFit from scratch with pure Pytorch?** just for learning pourposes.

No. But the fast.ai implementation is pure PyTorch. So you'll just have to look into the source code of fastai.

**Comment by StephennFernandes** [comment]
Hey i tried the implemntation but with my use case i face very weird issues. 

the language im working with is goan konkani code-named "gom" 
however it has very little data on wikipedia. i have collected data from different sources like archived notebooks, private access from organizations etc. 
the data contains 49 million words , 3.7 million sentences. 

ive added this large .txt file into the dir where where the wiki script is. 

but on training im getting a perplexity score of 3300 and even after 4 epochs its only down to 3200 

also the iterations on every epochs is also quite quick as in around 2:30 mins per epoch. 
secondly i didnt even change the batch size because 128 bs seems to fit on my 8GB memory. 

all of this is quite strange actually

**Comment by floleuerer** [comment]
Thats really strange. 

The script expects one txt per wiki-article in `data/<lang-code>wiki/docs/sampled/`. The DataLoader will tokenize the txts and cache them in `sampled_tok`. So try to provide the documents as single txts in the `sampled` folder and please try again. I think that's the cause for the issue.

49 million words should be fine to train a lm (I usually aim for >100 mio but depending on the language and number of wiki articles its much less). How many batches do you get (`len(dls.train)`)?

**Comment by StephennFernandes** [comment]
I am getting 314 batches, while the count of text files in the all/ dir  are around 4,600  
which is quite strange again. 

is it possible to keep my large corpus.txt file as it is or should i somehow break it down into smaller bits of multiple files. 

the data in there is quite continuous as in, all extra whitespaces have been removed. hence it would be really hard to differentiate between different articles to seperate contents from that txt file.

**Comment by floleuerer** [comment]
Yes I think it's due to the lange corpus.txt. E.g. for 46 million words I'd have about 80.000 txt files in the `sampled/` directory and ~10.000 batches in the training dataloader. also make sure you delete the cached `sampled_tok` dir after each try. Otherwise you won't see any changes because the tokenization will be skipped and the data will be read from the cache directory.

**Comment by StephennFernandes** [comment]
Okay i see ... so its okay right to keep my large txt file as it is and paste it in the `sampled/` dir

**Comment by StephennFernandes** [comment]
My notebook get stuck in the loop of dataloaders, i ran the process for over 9 hrs now and its still stuck there. 

I guess the multi-threading happens on per txt article file basis and when it encounters my large txt file one thread is processing this large file. thus its suck there forever.
