### ISSUE TITLE
getting index out of bounds error 

### ISSUE THREAD

**Issue by StephennFernandes** [floleuerer/fastai_ulmfit#3]
So i am training the above model in the exact same hyperparamters as you on a v100 notebook instance. 

but upon the validation data iter run i get the error: 
`IndexError: index 4512 is out of bounds for dimension 0 with size 128`

I tried clearing everthing and restarting the notebobk several times, but no luck. dont know what sems to be the issue ? 
Ive aso added some of my text files to the data as i had mentioned in my previous issue. 
Ive managed to chunk my one large text file into multiple files by splititing them into multiple files of 100 lines each file.

**Comment by floleuerer** [comment]
Hi Stephen, 

could you please share your notebook and the full stack trace?

Thanks Florian

**Comment by StephennFernandes** [comment]
![Screenshot from 2021-04-15 22-05-37](https://user-images.githubusercontent.com/32235549/114930368-87ee9980-9e52-11eb-96c6-d80d9284b6ef.png)

**Comment by StephennFernandes** [comment]
It has to do something with the delegates decorator, i had already some issues with the delgates decorator on other projects too...

**Comment by StephennFernandes** [comment]
Hey @floleuerer i was able to find a fix on this it was just the fastai version issue, it seems to be an issue with fastai 2.3 and works fine with version 2.2
