### ISSUE TITLE
Does training with large batch-size result in any loss in accuracy or any sort of losses in train or validation. 

### ISSUE THREAD

**Issue by StephennFernandes** [floleuerer/fastai_ulmfit#4]
Hey, I have a free V100 Cloud instance and i am extremely tight on budget. i was wondering given how sensitive ULMFIT can be to Hparams, does setting batch size to 512 cause any sort of loss in accuracy of strong convergence while training ULMfit ?

**Comment by floleuerer** [comment]
Hi Stephen,

I tried batch sizes from 64 - 256 and all gave quite similar results regarding loss / perplexity. The speedup from 128 to 256 was about 15% if I remember correctly so don't expect a hughe difference in training time.

Florian

**Comment by StephennFernandes** [comment]
Hey @floleuerer , I trained with 128 batch size and it consumed 5.5 gb of my 8 GB of GPU memory on the entire first epoch. 


But while the validation epoch ran after the training epoch. the system crashed. It was because I observed the ram got bumped up to its maximum capacity. I have 16GB of Ram and I think it's the cause. 

How much ram did you use and can you tell me the concept of sampled dir in the data directory. 

It contains only a handful of data files in it and perhaps the model only trains on that amount of data. Also I dumped all of my extra TXT files into the "sampled" file directory as well as the "all" file directory. 

How do I go with placing my additional files into both "all" and "sampled" directories.

**Comment by floleuerer** [comment]
Step 1 the wikiextractor will extract the whole wiki dump into "all" and samples by default 160000 documents into the "sampled" folder. the training notebook then reads the files in "sampled" for training (the tokenizerer caches it's data in sampled_tok so delete this folder if you have issues to make sure the tokenization will be forced to run again). 

I'm using 64 gb ram but I don't know how much is required - I think 16 GB should be enough. make sure to restart the notebook before every run.

**Comment by StephennFernandes** [comment]
@floleuerer  man tired to implement the model on 32 batch size on a 32 GB VM instance with 16GB Nvidia T4. 
Also chances the num of cores to match the 16 cores in the VMs CPU specs. 

Still the se crash, I really don't understand why it's happening. I have literally not touched any of your code. Just added wandb logging. 

And I checked it definately Ram issue, as just before crashing the ram usage jumps all the way up and then the program crashes
