### ISSUE TITLE
how to train ulmfit on other downstream task like POS 

### ISSUE THREAD

**Issue by StephennFernandes** [floleuerer/fastai_ulmfit#5]
@floleuerer , So i pre-trained ulmfit on Konkani Language yielding perplexity score of 11.49 and 11.65 for forward and backward language modeling, and similarly while fine tuning on a pos dataset i was able to get perplexity score of 31 and 33 for fwd and bwd. 

But the place where i am stuck at right now is pos classification. 
The language i am working with doesn't have text classification dataset. it however has pos tagging dataset. 

the fastai dataloader is currently constrained to a text classifier , do you know how to modify the fastai dataloader to use it for pos tagging in the given fine tuned ulmfit model ???

**Comment by floleuerer** [comment]
Glad to hear that you trained the lm successfully. No sorry unfortunately I don't know how to use ULMFiT for POS tagging. By default ULMFiT can be used for classification and regression.
