### ISSUE TITLE
Fastai with NL language

### ISSUE THREAD

**Issue by Manel-Hik** [floleuerer/fastai_ulmfit#8]
Hi;
Thanks for this usefull library: fastai-ulmfit
I'm doing text classification on nl text data;
when using this function: 
url = 'https://bit.ly/ulmfit-nlwiki'
tok = tokenizer_from_pretrained(url)
I got an error: KeyError: 'tokenizer'
but with different language deutch or italian, it works.
Could you please help me figure out this?
Thanks

**Comment by floleuerer** [comment]
Hi, 

the tokenizer-config was missing in the uploaded model. I've fixed that issue now. Could you please try again?

Florian

**Comment by Manel-Hik** [comment]
Yes it works
Thank you
