### ISSUE TITLE
Fastai with Portuguese Language

### ISSUE THREAD

**Issue by brendasalenave** [floleuerer/fastai_ulmfit#9]
Hi! 

I am trying to use the fastai_ulmfit library to classify texts in Portuguese. However, when I try to use the _tokenizer_from_pretrained_ function I receive a "_ReadError: not a gzip file"_ error. 

I tried using the following: 

> url = 'https://bit.ly/ulmfit-ptwiki'
> tok = tokenizer_from_pretrained(url)

When testing with some other different languages, it works.
How can I figure out this?

Thank you!

**Comment by floleuerer** [comment]
Hi,

I think Bitly blocked the link and I don't know why. I'll try to fix that but that might take a while. The following link should work:
http://meansqua.red/files/ulmfit/ulmfit_ptwiki.tgz

Best regards
Florian
